# Generated by Django 5.2.14 on 2026-05-20 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('aircraft', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('flight_level', models.IntegerField(blank=True, null=True)),
                ('block_fuel', models.FloatField(blank=True, null=True)),
                ('trip_fuel', models.FloatField(blank=True, null=True)),
                ('efob_arrival', models.FloatField(blank=True, null=True)),
                ('approach_type', models.CharField(blank=True, default='', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('imported_from_simbrief', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
    ]
